/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_echo_server;

public class App {
    public static void main(String[] args) {
        int portNumber = 1234;
        EchoServer echoServer = new EchoServer();
        echoServer.start(portNumber);
    }
}
